apiVersion: v1
kind: Pod
metadata:
  name: embed
  labels:
    arch: embed
spec:
  containers:
    - name: embed
      image: ghcr.io/ajavageek/wasm-kubernetes:embed
---
apiVersion: v1
kind: Service
metadata:
  name: embed
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    arch: embed
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: embed
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /embed(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: embed
                port:
                  number: 3000
