apiVersion: v1
kind: Pod
metadata:
  name: wasm
  namespace: regular
  labels:
    arch: wasm
spec:
  containers:
    - name: wasm
      image: wasm-kubernetes:wasm
---
apiVersion: v1
kind: Pod
metadata:
  name: native
  namespace: regular
  labels:
    arch: native
spec:
  containers:
    - name: native
      image: wasm-kubernetes:native
---
apiVersion: v1
kind: Service
metadata:
  name: wasm
  namespace: regular
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30000
  selector:
    arch: wasm
---
apiVersion: v1
kind: Service
metadata:
  name: native
  namespace: regular
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30001
  selector:
    arch: native
