apiVersion: v1
kind: Namespace
metadata:
  name: regular
---
apiVersion: v1
kind: Pod
metadata:
  name: embed
  namespace: regular
  labels:
    arch: embed
spec:
  containers:
    - name: embed
      image: ghcr.io/ajavageek/wasm-kubernetes:embed
---
apiVersion: v1
kind: Pod
metadata:
  name: native
  namespace: regular
  labels:
    arch: native
spec:
  containers:
    - name: native
      image: ghcr.io/ajavageek/wasm-kubernetes:native
---
apiVersion: v1
kind: Service
metadata:
  name: embed
  namespace: regular
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30000
  selector:
    arch: embed
---
apiVersion: v1
kind: Service
metadata:
  name: native
  namespace: regular
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30001
  selector:
    arch: native
