apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasmedge
handler: wasmedge
---
apiVersion: v1
kind: Pod
metadata:
  name: runtime
  labels:
    arch: runtime
spec:
  containers:
    - name: runtime
      image: ghcr.io/ajavageek/wasm-kubernetes:runtime
  runtimeClassName: wasmedge
---
apiVersion: v1
kind: Service
metadata:
  name: runtime
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30001
  selector:
    arch: runtime
